### ISSUE TITLE
DNF version lock for kernel version

### ISSUE THREAD

**Issue by syaifurrizal** [rpm-software-management/dnf-plugins-core#501]
Hi, I would like to suggest that there are an option to do soft lock for kernel version. 

Means it will keep a locked version but it still do install the newest kernel to try instead that it will just ignore new kernel update (it's act like 2nd safe boot).

**Comment by pkratoch** [comment]
Hi, there is a bugzilla that describes the same issue: https://bugzilla.redhat.com/show_bug.cgi?id=2229991 Therefore, I am closing this as to not have a duplicate.
