### ISSUE TITLE
No  local plugin on rhel

### ISSUE THREAD

**Issue by bdouxx** [rpm-software-management/dnf-plugins-core#503]
hi,

I have a very slow internet connection with redhat VM (with Vagrant),

In order to update all VM, I want to share all downloaded rpm between VM.
in this site they talk about " dnf local plugin"  to do this
https://fedoramagazine.org/use-the-dnf-local-plugin-to-speed-up-your-home-lab/

but I can't find local files in dnf-plugin-core 4.0.21

**Comment by m-blaha** [comment]
The plugin is packaged as `python3-dnf-plugin-local`, but unfortunately it's not delivered and supported for RHEL, only in Fedora.

**Comment by bdouxx** [comment]
OK.
I will try another method.
Thanks

**Comment by ppisar** [comment]
For  RHEL support, please contact RHEL support <https://access.redhat.com/support/>.
