### ISSUE TITLE
Syntax of `dnf config-manager --setopt`

### ISSUE THREAD

**Issue by korpe1** [rpm-software-management/dnf-plugins-core#505]
The docs says:

> `dnf config-manager [options] <section>...`
> ...
> `<section>`
This argument can be used to explicitly select the configuration sections to manage. A section can either be `main` or a repoid. If not specified, the program will select the `main` section and each repoid used within any `--setopt` options. A repoid can be specified using globs.
> ...
> `--setopt=<option>=<value>`
Set a configuration option. To set configuration options for repositories, use `repoid.option` for the `<option>`. Globs are supported in repoid.
>..
>`dnf config-manager --save --setopt=*.proxy=http://proxy.example.com:3128/ <repo1> <repo2>`
    Update proxy setting in repositories with repoid <repo1> and <repo2> and make the change permanent.

And this brings to my mind the following questions:
What is the difference between `dnf config-manager --save --setopt=test.proxy=example.com` and `dnf config-manager --save --setop=proxy=example.com test`?

If " If not specified, the program will select the `main` section and each repoid used within any `--setopt` options. A repoid can be specified using globs." is true, does `dnf config-manager --save --setopt=*.proxy=http://proxy.example.com:3128/ <repo1> <repo2>` will change repo1, repo2 and main confs?

**Comment by korpe1** [comment]
Also, what `dnf config-manager --setopt=proxy=example.com test` (i.e. `--set-opt` without `--save`) do?

**Comment by jan-kolarik** [comment]
Hello, @korpe1.

> What is the difference between dnf config-manager --save --setopt=test.proxy=example.com and dnf config-manager --save --setop=proxy=example.com test?

In this use case, I believe the behavior of both commands is the same.  However, if you were to use an additional option, such as `--set-enabled`, the provided `<section>` argument would be passed to this option, resulting in a different behavior.

> If " If not specified, the program will select the main section and each repoid used within any --setopt options. A repoid can be specified using globs." is true, does dnf config-manager --save --setopt=*.proxy=http://proxy.example.com:3128/ <repo1> <repo2> will change repo1, repo2 and main confs?

Hmm, I believe the documentation could be enhanced in this regard. Generally, it appears that mixing the `repoid` selector in the `--setopt` option with an explicit list of sections is not a good idea. The explicit list of sections (repos) takes precedence over the `repoid` selector. The main section is written only if no `repoid` in `--setopt` is used and the explicit section list contains the main section or is empty.

Therefore, your example modifies only `repo1` and `repo2`.

> Also, what dnf config-manager --setopt=proxy=example.com test (i.e. --set-opt without --save) do?

As the `--setopt` is a global option intended for setting temporary runtime configurations, the `--save` option was introduced to make these changes permanent without altering the global behavior by the `config-manager` plugin.

In your specific use case, setting `proxy=example.com` using `--setopt` applies only for the duration of the `config-manager` command's runtime which is useless there. But, it can be useful, for instance, when inspecting the entire configuration before making permanent changes. You can achieve this by using a command like: `dnf config-manager --setopt=zchunk=0 --dump`.
