### ISSUE TITLE
Will these plugins be rewritten to C for DNF5?

### ISSUE THREAD

**Issue by korpe1** [rpm-software-management/dnf-plugins-core#506]
[DNF5](https://github.com/rpm-software-management/dnf5) is becoming more widely adopted, so will these plugins be rewritten to C?

**Comment by kontura** [comment]
Yes, we already have some.

They might take the form of [dnf5 plugins](https://github.com/rpm-software-management/dnf5/tree/main/dnf5-plugins), [libdnf5 plugins](https://github.com/rpm-software-management/dnf5/tree/main/libdnf5-plugins) or they might be integrated differently but we want to preserve the functionality where it makes sense.

**Comment by j-mracek** [comment]
There is a tracking issue - https://github.com/rpm-software-management/dnf5/issues/389.

I am closing the issue as a resolve because there is a tracking issue in DNF5 project

**Comment by korpe1** [comment]
> Yes, we already have some.
> 
> They might take the form of [dnf5 plugins](https://github.com/rpm-software-management/dnf5/tree/main/dnf5-plugins), [libdnf5 plugins](https://github.com/rpm-software-management/dnf5/tree/main/libdnf5-plugins) or they might be integrated differently but we want to preserve the functionality where it makes sense.

How libdnf5 plugins works? Libdnf5 is library so, eh? 😅

**Comment by kontura** [comment]
We have a tutorial in the docs: https://dnf5.readthedocs.io/en/latest/tutorial/plugins/libdnf5-plugins.html or you can check the linked code.
Basically the library specifies several hooks like `pre_base_setup`, `post_base_setup`, `pre_transaction`... and you can trigger your own code at these points changing the library behavior.

**Comment by korpe1** [comment]
> We have a tutorial in the docs: https://dnf5.readthedocs.io/en/latest/tutorial/plugins/libdnf5-plugins.html or you can check the linked code. Basically the library specifies several hooks like `pre_base_setup`, `post_base_setup`, `pre_transaction`... and you can trigger your own code at these points changing the library behavior.

Sorry the stupid question, but I think libraries are for borrowing code... so, what is the point of make plugins for them? Plugins makes sense for Firefox, Gedit, etc. applications, but what is point of plugins inside libraries?

**Comment by kontura** [comment]
The way I see it plugins for applications allow adding specific features and enable customization. In the same spirit you can add features and enable customization for a library. I think the important thing this enables is sharing these plugins among users of the library while they don't have to be part of the library.

**Comment by korpe1** [comment]
> The way I see it plugins for applications allow adding specific features and enable customization. In the same spirit you can add features and enable customization for a library. I think the important thing this enables is sharing these plugins among users of the library while they don't have to be part of the library.

Hmm, maybe it makes sense, but is right to say that plugins are a niche thing in libraries? At the end, libraries are set of code snippets/functions for certain topic and usually you want to develop libraries directly instead develop plugins for it.

**Comment by kontura** [comment]
> Hmm, maybe it makes sense, but is right to say that plugins are a niche thing in libraries? 

Perhaps, right now I can think of only one more example: [libpurple](https://keep.imfreedom.org/pidgin/pidgin/). However I am sure there is more.

**Comment by korpe1** [comment]
> > Hmm, maybe it makes sense, but is right to say that plugins are a niche thing in libraries?
> 
> Perhaps, right now I can think of only one more example: [libpurple](https://keep.imfreedom.org/pidgin/pidgin/). However I am sure there is more.

Anyway, thank you for sharing thoughts with me :)
