### ISSUE TITLE
dnf config-manager--set-enabled

### ISSUE THREAD

**Issue by cgwalters** [rpm-software-management/dnf-plugins-core#565]
The CI on one of my projects got upgraded to dnf5, which broke it because `dnf config-manager --set-enabled=$repo` no longer works.

For reference, here's a [github search for that invocation](https://github.com/search?q=%22dnf+config-manager+--set-enabled%22+-is%3Afork&type=code) - excluding forks there's almost 5000 references to it on Github.

I don't think it makes sense for all of them to rewrite.

**Comment by m-blaha** [comment]
Thanks for the report! The config-manager command has changed significantly from dnf4 to dnf5, now offering many more features.
To enable a repository, use the new syntax: `dnf config-manager setopt repoid.enabled=1`.
The dnf team will discuss adding a compatibility `--set-enabled` option at the next team meeting.

**Comment by cgwalters** [comment]
Do you have any tracking of dnf4 -> dnf5 compatibility issues? If none exists, it seems like it'd at least make sense to have a github label for it.

**Comment by m-blaha** [comment]
That's a good idea.
Let me close this ticket here and move it to dnf5 project. The compatibility issue label make sense there.
